// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import RemovalsController from "./removals_controller"
import TabsController from "./tabs_controller"

application.register("tabs", TabsController)
application.register("removals", RemovalsController)
